PATH_DATA = ENV["PATH_DATA"]
PATH_RES = ENV["PATH_RES"]
ARCHIVE = ENV["ARCHIVE"]
#sh or llsubmit
EXECCOM = ENV["EXECCOM"]
MODULELOAD = ENV["MODULELOAD"]
#SPOT6
#0 process all, 1 process only last period
REALTIMEMODE = 1
SPOT6CARDDIR=ENV["SPOT6CARDDIR"]
SPOT6QUEUE=ENV["SPOT6QUEUE"]
SPOT6GEN_HTMLANDPNG = ENV["SPOT6GEN_HTMLANDPNG"]
