# DESCRIPTION
#       Agileap: AGILE Observatory Aperture Photometry Analysis
# NOTICE
#      Any information contained in this software
#      is property of the AGILE TEAM and is strictly
#      private and confidential.
#      Copyright (C) 2005-2020 AGILE Team.
#          Bulgarelli Andrea <andrea.bulgarelli@inaf.it>
#      All rights reserved.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys

class FileUtils:
	#convert the Fermi/LAT aperture photometry file generated by a modified version of aperture.pl (that add the counts column) 
	def convertFermiAperturePlToAGILEAp(self, filenameinput, binsize, filenameoutput):
		fileclean = open(filenameoutput + ".ap","w")
		with open(filenameinput, "r") as ins:
			for line in ins:
				if(line != ""):
					val = line.split(" ")
					tstart = float(val[0])
					tstart = (tstart - 53005.0) * 86400.0 - binsize/2
					tstop = tstart + binsize
					exp = val[5]
					cts = int(val[6])

					line = str(tstart) + ' ' + str(tstop) + ' ' + exp + ' ' + str(cts).strip()            
					fileclean.write(line + "\n")

		fileclean.close()
